# Generated by Django 4.1 on 2022-08-10 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amenazas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('initials', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriesIncidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('appreciation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.appreciation')),
            ],
        ),
        migrations.CreateModel(
            name='Risks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxValue', models.IntegerField()),
                ('minValue', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Threats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('initials', models.CharField(max_length=10)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.goods')),
            ],
        ),
        migrations.DeleteModel(
            name='Factor',
        ),
        migrations.RemoveField(
            model_name='threat',
            name='byGroup',
        ),
        migrations.RemoveField(
            model_name='threat',
            name='valor',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Threat',
        ),
        migrations.DeleteModel(
            name='Valor',
        ),
        migrations.AddField(
            model_name='incidents',
            name='incidenceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.incidentstypes'),
        ),
        migrations.AddField(
            model_name='categoriesincidents',
            name='incidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.incidents'),
        ),
    ]
