# Generated by Django 4.1 on 2022-08-10 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenazas', '0002_appreciation_categories_categoriesincidents_goods_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Categorie',
        ),
        migrations.RenameModel(
            old_name='CategoriesIncidents',
            new_name='CategoriesIncident',
        ),
        migrations.RenameModel(
            old_name='Goods',
            new_name='Good',
        ),
        migrations.RenameModel(
            old_name='Incidents',
            new_name='Incident',
        ),
        migrations.RenameModel(
            old_name='IncidentsTypes',
            new_name='IncidentsType',
        ),
        migrations.RenameModel(
            old_name='Measures',
            new_name='Measure',
        ),
        migrations.RenameModel(
            old_name='Risks',
            new_name='Risk',
        ),
        migrations.RenameModel(
            old_name='Threats',
            new_name='Threat',
        ),
    ]
