# Generated by Django 4.1 on 2022-08-11 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenazas', '0004_active_activetype_factor_procedure_process_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='active',
            old_name='ActiveType',
            new_name='activeType',
        ),
        migrations.RenameField(
            model_name='factor',
            old_name='factortype',
            new_name='factorType',
        ),
    ]
