# Generated by Django 4.1 on 2022-08-16 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amenazas', '0005_rename_activetype_active_activetype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CriticalityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('interruptTime', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ParValuesValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=50)),
                ('probability', models.CharField(max_length=50)),
                ('occurrence', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='RangeFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minValor', models.IntegerField()),
                ('maxValor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.incident')),
                ('rangeFactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.rangefactor')),
            ],
        ),
        migrations.CreateModel(
            name='SafetyFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='factor',
        ),
        migrations.RemoveField(
            model_name='vulnerability',
            name='activeType',
        ),
        migrations.RemoveField(
            model_name='activetype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='active',
        ),
        migrations.RemoveField(
            model_name='process',
            name='factor',
        ),
        migrations.RemoveField(
            model_name='process',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='process',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='threat',
            name='description',
        ),
        migrations.AddField(
            model_name='active',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='process',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='active',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='active',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activetype',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='threat',
            name='availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='threat',
            name='confidentiality',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='threat',
            name='integrity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='threat',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='threat',
            name='threatType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.threattype'),
        ),
        migrations.AlterField(
            model_name='threattype',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='threattype',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Factor',
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
        migrations.DeleteModel(
            name='Vulnerability',
        ),
        migrations.AddField(
            model_name='processprocedure',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.procedure'),
        ),
        migrations.AddField(
            model_name='processprocedure',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.process'),
        ),
        migrations.AddField(
            model_name='incident',
            name='active',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.active'),
        ),
        migrations.AddField(
            model_name='incident',
            name='threat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.threat'),
        ),
        migrations.AddField(
            model_name='criticalityassessment',
            name='active',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.active'),
        ),
        migrations.AddField(
            model_name='criticalityassessment',
            name='processProcedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.processprocedure'),
        ),
        migrations.AddField(
            model_name='criticalityassessment',
            name='rangeFactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.rangefactor'),
        ),
        migrations.AddField(
            model_name='assetvaluation',
            name='active',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.active'),
        ),
        migrations.AddField(
            model_name='assetvaluation',
            name='processProcedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.processprocedure'),
        ),
        migrations.AddField(
            model_name='assetvaluation',
            name='safetyFactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.safetyfactor'),
        ),
        migrations.AddField(
            model_name='assetvaluation',
            name='valoration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenazas.parvaluesvaluation'),
        ),
        migrations.AddField(
            model_name='process',
            name='processType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amenazas.processtype'),
        ),
    ]
