# Generated by Django 4.1 on 2022-08-17 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenazas', '0006_assetvaluation_criticalityassessment_incident_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threattype',
            name='name',
        ),
    ]
