# Generated by Django 4.1 on 2022-08-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenazas', '0007_remove_threattype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='interruptTime',
            field=models.TimeField(),
        ),
    ]
