# Generated by Django 4.1 on 2022-08-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenazas', '0008_alter_incident_interrupttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
