# Generated by Django 4.1 on 2022-08-17 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amenazas', '0009_processtype_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='name',
        ),
    ]
