# Generated by Django 4.1 on 2022-08-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenazas', '0010_remove_process_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedure',
            name='name',
        ),
        migrations.AddField(
            model_name='procedure',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
