# Generated by Django 4.1 on 2022-08-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenazas', '0011_remove_procedure_name_procedure_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='parvaluesvaluation',
            name='code',
            field=models.CharField(default='', max_length=25),
        ),
    ]
