# Generated by Django 4.1 on 2022-08-17 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amenazas', '0014_alter_assetvaluation_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetvaluation',
            name='active',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amenazas.active'),
        ),
    ]
